CFG = {
    'frames_dir'     : 'data/processed/frames_mosaic',
    'img_size'       : (224, 224),
    'seq_len'        : 5,
    'val_split'      : 0.15,
    'test_split'     : 0.15,
    'batch_size'     : 8,
    'num_workers'    : 0,
    'epochs'         : 30,
    'lr'             : 1e-4,
    'weight_decay'   : 1e-4,
    'num_classes'    : 3,
    'pretrained'     : True,
    'checkpoint_dir' : 'results/checkpoints',
}